apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netflix-clone
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/user-service
    repoURL: https://github.com/yourname/netflix-microservices-clone.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true