apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/adip47/netflix-microservices-clone.git
    targetRevision: helm-charts
    path: netflix-helm-charts
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
