# GitHub Actions CI/CD pipeline
name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Build and push image
        run: echo 'docker build && push'
      - name: Deploy with Helm
        run: echo 'helm upgrade --install'